
ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com/"
drosera_rpc = "https://relay.hoodi.drosera.io/"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.flashloan_volume_trap]
path = "out/FlashloanVolumeTrap.sol/FlashloanVolumeTrap.json"
response_contract = "0x0000000000000000000000000000000000000000"
response_function = ""
cooldown_period_blocks = 20
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 8
private_trap = true
whitelist = ["0x1763c654F2b4a13a6C08058434bdc4Cc7B7EcE90"]
